### ISSUE TITLE
Enhancement: Option to have shot limits applied to flags stolen by thief

### ISSUE THREAD

**Issue by Zehra** [allejo/shotLimitZone#5]
An option of shotZoneLimits applying to specified flags which originate from the shotLimitZone, regardless if they are stolen would be nice.

**Currently:**
PlayerA grabs Laser from shotLimitZone with 5 shots set as limit.
PlayerA fires 4 rounds, leaving 1 shot remaining.
PlayerB steals PlayerA's Laser flag with Thief.
PlayerB has Laser flag with shot limits from server.

**Enhancement**
PlayerA grabs Laser from shotLimitZone with 5 shots and "thief" option added.
(Thief option causes limits to apply, even if the flag is stolen by thief.)
PlayerA fires 4 rounds, leaving 1 shot remaining.
PlayerB steals PlayerA's Laser flag with Thief.
PlayerB has Laser flag with 1 shot left.

**Comment by allejo** [comment]
Instead of introducing a new "thief" option to the map object, I'd just make respecting flag steals obey limitations placed by a `shotlimitzone`. The goal of this plugin is to add shot limits to flags grabbed from a zone meaning these flags have said shot limit and flag steals should carry over the remaining shot count.

**Comment by allejo** [comment]
I'd welcome a pull request for the behavior I stated above, @Zehra 😄
